### ISSUE TITLE
Toast notification when feedback text field is empty and user click the post button

### ISSUE THREAD

**Issue by baquer** [fossasia/susi_iOS#504]
**Actual Behaviour**

No  notification when user click the post button with empty text field

**Expected Behaviour**

It should alert the user about  the feedback text field

**Would you like to work on the issue?**

Yes

**Comment by baquer** [comment]
@jogendra , actually in this issue , when the user is logged-in and try to post feedback with empty feedback text field , it is not showing any alert , while when the user is not logged-in and try to post the feedback it pops up the alert controller for login.  
Here is the video url of this issue
[Video URL](https://youtu.be/micK9M343gQ) .Please see this issue.

**Comment by jogendra** [comment]
@baquer Yes, this is left intentionally. When the user is logged-in and clicks post button, there is not any alert because the user knows that it does not make any sense to get it clicked without any text so there is no need of any alert.
But when the user is not logged-in we show the alert to login user so that user come to know that only logged-in user can post feedback.

**Comment by baquer** [comment]
thanks @jogendra  , for explaining this to me ☺️
now i am closing this issue.
