### ISSUE TITLE
Ability to mark/star messages

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_iOS#53]

**Comment by chiragw15** [comment]
Discuss this once with Mario if marking the message is actually required? We do have it on android but I am not sure about that. There are chances that it may be removed as it is not much of a use.

**Comment by chashmeetsingh** [comment]
Will do when I come to this

**Comment by mariobehling** [comment]
I am not sure, if this is a priority now, cause this kind of "star" should be implemented in the server as well. So, messages show up as starred on all clients. 

@chiragw15 I think this is not the case at the moment with the Android app.

As a rule of thumb - if Google Assistant or Siri has it, then we should have it. If not, then it is lower priority.

**Comment by chiragw15** [comment]
@mariobehling In android app we have this feature to star the message but it is done locally only (storing it in android database) and not related to server. So, it won't be displayed on all clients. Google assistant doesn't have this feature too(don't know about siri). This is the reason I asked @chashmeetsingh to confirm it once from you. So, I think this can be delayed for now in IOS and other clients. And for android, what do you suggest? Since it is already implemented, should we remove it or keep it?

**Comment by chashmeetsingh** [comment]
Is there any use case for the same? Why are we actually starting the messages? @chiragw15

**Comment by chiragw15** [comment]
Not much but maybe a case when susi replies with something and user finds it important and may need it in future. So, he may star it and whenever in future he wants it, he may look up for it in starred messages. It has limited use thats why I am asking it to delay it for now.

**Comment by chashmeetsingh** [comment]
I suppose if something's impt. user would prefer to create an event, save in calendar or add in the notes. I guess that's why Siri or Assistant do not have this feature. What do you think?

**Comment by chiragw15** [comment]
Yup we have an issue for reminder skill. https://github.com/fossasia/susi_skill_data/issues/108. We can also create a skill to add something to notes.

**Comment by mariobehling** [comment]
Ok, I am closing this for now as it does not seem a priority. Thanks for your input!
