### ISSUE TITLE
Reduce build time on travis

### ISSUE THREAD

**Issue by chashmeetsingh** [fossasia/susi_iOS#57]
For this we will need to:
- Include Pods folder, since it's going to remain the same unless versions updates
- Removing test and clean from the build script, they are not required

Thoughts @mariobehling @niranjan94 ?

**Comment by niranjan94** [comment]
- Downloadable dependencies should **not** be added to the repo. So that means, we shouldn't add the Pods folder. And anyway, travis [caches pods](https://docs.travis-ci.com/user/caching/#CocoaPods). So that's fine.
- Why do you want to remove tests from the build ? Proper tests are an important part of any project. Infact, you should be adding more test cases to this project too

**Comment by chashmeetsingh** [comment]
Hmm ok.

I am referring to the command test and clean in the build script, they aren't needed. If that's removed the UI test will run even then.
